server:
  port: 9920

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://smallsmart.top/forum?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: password
  mail:
    host: smtp.qq.com
    username: jgxq@foxmail.com
    password: rwclfxtpyvgdddeb
    default-encoding: UTF-8
  redis:
    host: smallsmart.top
    port: 6379

JWTParam:
  cookieDomain: smallsmart.top
  cookieSecure: false

# 静态资源存储地址
web:
  upload-path: file:/usr/springuploads/